# basic info
user_name: "yanjujijd"
repo_name: "cv-arxiv-daily"

show_badge: false
max_results: 50

publish_readme: true
publish_gitpage: true
publish_wechat: false

# file path 
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords
keywords:
  "Context Engineering & Prompting": 
    "filters": ["Context Engineering", "Prompt Engineering", "In-Context Learning", "Few-Shot Prompting", "Instruction Tuning", "Context-Aware Models"]
  "Retrieval-Augmented Generation (RAG)": 
    "filters": ["Retrieval-Augmented Generation", "Information Retrieval", "Vector Database", "Dense Retrieval", "Knowledge Grounding", "Query Transformation", "Reranking"]
  "Context Optimization & Management": 
    "filters": ["Context Management", "Context Compression", "Prompt Compression", "Context Window", "Token Optimization", "Information Density", "Context Filtering", "Summarization"]
  "LLM Reasoning & Strategy": 
    "filters": ["Chain-of-Thought", "Step-by-Step Reasoning", "Self-Correction", "In-Context Reasoning", "Prompt Chaining", "Decomposition", "Logical Reasoning"]
  "Agentic Architecture & Orchestration": 
    "filters": ["LLM Agent", "Tool-Augmented LLMs", "Function Calling", "Agentic Workflow", "Orchestration", "Agent Memory", "State Management", "LLM as Controller"]
#   "DA & DG":
#     filters: ["Domain Adaptation", "Unsupervised Domain Adaptation", "Source-free Domain Adaptation", "Test-time Domain Adaptation",
#       "Domain Generalization", "Source-free Domain Generalization", "Test-time Domain Generalization"]
#   "VLM":
#     filters: ["Vision Language Model", "Vision Language Models", "Vision-Language Model", "Vision-Language Models"]
#   "Prompt":
#     filters: ["Prompt Tuning", "Prompt Learning", "Prompt", "Prompts"]
#   "Causal Learning":
#     filters: ["Causal Inference", "Causal Model", "Causal Discovery", "Causal Reasoning"]
